name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Log in to the Docker CLI
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      # Build dev image of client for tests
      - run: docker build -t alonyevt/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true alonyevt/react-test npm test
      # Build production images
      - run: docker build -t alonyevt/multi-client ./client
      - run: docker build -t alonyevt/multi-nginx ./nginx
      - run: docker build -t alonyevt/multi-server ./server
      - run: docker build -t alonyevt/multi-worker ./worker
      # Push the images to the Docker hub
      - run: docker push alonyevt/multi-client
      - run: docker push alonyevt/multi-nginx
      - run: docker push alonyevt/multi-server
      - run: docker push alonyevt/multi-worker
      # Generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      # Deploy to Elastic Beanstalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-gh
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
